name_jcs = input("Enter your name: ")
age_jcs = input("Enter your age: ")
course_jcs = input("Enter your course: ")
university_jcs = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_jcs)
print("Age:", age_jcs)
print("Course:", course_jcs)
print("University:", university_jcs)
